import { prisma } from "@/lib/prisma";

/**
 * Structured escalation summary for manufacturer support.
 */
export interface EscalationSummary {
  /** Product name (if known) */
  productName: string | null;
  /** Article number (if known) */
  articleNumber: string | null;
  /** Retailer name */
  retailer: string | null;
  /** Summary of the problem from chat messages */
  problemDescription: string;
  /** Steps the user/AI tried to resolve the issue */
  stepsTried: string[];
  /** Whether any photos were sent in the chat */
  hasPhotos: boolean;
  /** The full formatted summary text, ready for copy-to-clipboard */
  formattedText: string;
}

/**
 * Build an escalation summary from a chat session's messages and product context.
 *
 * Scans the conversation to extract:
 * - The initial problem description (first user message or intake data)
 * - Steps tried (assistant suggestions that got follow-up)
 * - Whether photos were attached
 *
 * Returns a pre-formatted text block suitable for pasting into a support email/form.
 */
export async function buildEscalationSummary(
  sessionId: string
): Promise<EscalationSummary | null> {
  const session = await prisma.chatSession.findUnique({
    where: { id: sessionId },
    select: {
      productId: true,
      messages: {
        orderBy: { createdAt: "asc" },
        select: { role: true, content: true, imageUrl: true },
      },
    },
  });

  if (!session) return null;

  // Resolve product info
  let productName: string | null = null;
  let articleNumber: string | null = null;
  let retailer: string | null = null;

  if (session.productId) {
    const product = await prisma.product.findUnique({
      where: { id: session.productId },
      select: {
        product_name: true,
        article_number: true,
        source_retailer: true,
      },
    });
    if (product) {
      productName = product.product_name;
      articleNumber = product.article_number;
      retailer = product.source_retailer;
    }
  }

  const userMessages = session.messages.filter((m) => m.role === "user");
  const assistantMessages = session.messages.filter(
    (m) => m.role === "assistant"
  );
  const hasPhotos = session.messages.some((m) => m.imageUrl != null);

  // Problem description: use the first 1-2 user messages
  const problemParts = userMessages
    .slice(0, 2)
    .map((m) => m.content)
    .filter(Boolean);
  const problemDescription =
    problemParts.join("\n") || "No problem description provided.";

  // Steps tried: extract numbered steps from assistant messages
  const stepsTried: string[] = [];
  for (const msg of assistantMessages) {
    // Look for numbered instructions (1. Do this, 2. Do that)
    const stepMatches = msg.content.match(/^\d+\.\s.+$/gm);
    if (stepMatches) {
      for (const step of stepMatches) {
        const cleaned = step.replace(/^\d+\.\s+/, "").trim();
        if (cleaned.length > 10 && !stepsTried.includes(cleaned)) {
          stepsTried.push(cleaned);
        }
      }
    }
  }

  // Build formatted text
  const lines: string[] = [];
  lines.push("=== SUPPORT REQUEST ===");
  lines.push("");

  if (productName || articleNumber) {
    lines.push("PRODUCT INFORMATION:");
    if (productName) lines.push(`  Name: ${productName}`);
    if (articleNumber) lines.push(`  Article Number: ${articleNumber}`);
    if (retailer) lines.push(`  Purchased from: ${retailer}`);
    lines.push("");
  }

  lines.push("PROBLEM DESCRIPTION:");
  lines.push(problemDescription);
  lines.push("");

  if (stepsTried.length > 0) {
    lines.push("TROUBLESHOOTING STEPS ALREADY TRIED:");
    for (let i = 0; i < Math.min(stepsTried.length, 10); i++) {
      lines.push(`  ${i + 1}. ${stepsTried[i]}`);
    }
    lines.push("");
  }

  if (hasPhotos) {
    lines.push("NOTE: Photos of the issue were provided during chat troubleshooting.");
    lines.push("");
  }

  lines.push(
    "This summary was generated by Guid troubleshooting assistant after an unresolved chat session."
  );

  const formattedText = lines.join("\n");

  return {
    productName,
    articleNumber,
    retailer,
    problemDescription,
    stepsTried,
    hasPhotos,
    formattedText,
  };
}
